# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry

stages:
  - build
  - test
  - sec-scan
  - distribute
  - deploy

include:
  - project: 'hegerdes/templates'
    file: '/GitlabCI/kaniko-build.yml'

build-backend:
  extends: .build_template
  variables:
    COMMIT_TAG: $CI_COMMIT_TAG
    BUILD_IMAGE_TAG: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME
    CONTEXT: $CI_PROJECT_DIR/backend
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

build-frontend:
  extends: .build_template
  variables:
    COMMIT_TAG: $CI_COMMIT_TAG
    BUILD_IMAGE_TAG: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME
    CONTEXT: $CI_PROJECT_DIR/frontend
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

