stages:
  - build
  - test
  - sec-scan
  - distribute
  - deploy

include:
  - project: hegerdes/templates
    file: /gitlab/ci/defaults.yml
  - project: hegerdes/templates
    file: /gitlab/ci/kaniko-build.yml

build-backend:
  extends: .build_template
  variables:
    COMMIT_TAG: $CI_COMMIT_TAG
    BUILD_IMAGE_TAG: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME
    CONTEXT: $CI_PROJECT_DIR/backend
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

build-frontend:
  extends: .build_template
  variables:
    COMMIT_TAG: $CI_COMMIT_TAG
    BUILD_IMAGE_TAG: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME
    CONTEXT: $CI_PROJECT_DIR/frontend
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

package:
  image:
    name: alpine/helm
    entrypoint: [""]
  stage: build
  variables:
    CHART_VERSION: 0.1.2
  script:
    - helm package --app-version $CI_COMMIT_SHORT_SHA --version $CHART_VERSION charts
    - curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@reddvid-$CHART_VERSION.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"
