name: Docker-Build

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [backend, frontend]
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry GitHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into registry DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.MY_DOCKERHUB_USER }}
          password: ${{ secrets.MY_DOCKERHUB_TOKEN }}

      - name: Log in with Azure
        if: github.event_name != 'pull_request'
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.actor }}/reddvid:latest

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          cache-to: type=gha
          cache-from: type=gha
          context: ${{ matrix.app }}
          platforms: linux/amd64,linux/arm64
          sbom: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ github.actor }}/reddvid:${{ matrix.app }}-${{ github.ref_name }}
            ghcr.io/${{ github.actor }}/reddvid:${{ matrix.app }}-${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          # cosign sign ${{ github.actor }}/reddvid:${{ matrix.app }}@${{ steps.build-and-push.outputs.digest }}
          cosign public-key --key ${{ secrets.COSIGN_KEY_STORE }}
          cosign sign --key ${{ secrets.COSIGN_KEY_STORE }} \
            -a build-by=${{ env.GITHUB_ACTOR }} \
            -a repo=${{ env.GITHUB_REPOSITORY }} \
            -a repo-sha=${{ env.GITHUB_SHA }} \
            ${{ github.actor }}/reddvid@${{ steps.build-and-push.outputs.digest }}
          cosign sign --key ${{ secrets.COSIGN_KEY_STORE }} \
            -a build-by=${{ env.GITHUB_ACTOR }} \
            -a repo=${{ env.GITHUB_REPOSITORY }} \
            -a repo-sha=${{ env.GITHUB_SHA }} \
            ghcr.io/${{ github.actor }}/reddvid@${{ steps.build-and-push.outputs.digest }}
