name: Docker-Build

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]

permissions:
  contents: read
  packages: write
  id-token: write
  security-events: write

jobs:
  docker-build:
    strategy:
      fail-fast: false
      matrix:
        app: [backend, frontend]
    uses: hegerdes/helper-suite/.github/workflows/reusable-docker-build.yml@main
    with:
      build-context: ${{ matrix.app }}
      build-dockerfile: ${{ matrix.app }}/Dockerfile
      build-name: ${{ github.repository_owner }}/reddvid,ghcr.io/${{ github.repository_owner }}/reddvid
      build-tags: ${{ matrix.app }}-${{ github.ref_name }},${{ matrix.app }}-${{ github.ref_name }}
      build-cache: type=gha
      build-args: |
        COMMIT_HASH=${{ github.sha }}
        COMMIT_TAG=${{ github.ref_name }}
      build-labels: MAINTAINER=${{ github.repository_owner }}
      build-platforms: linux/amd64,linux/arm64
      extra-commands: echo "Checkout my website henrikgerdes.me"
    secrets:
      REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      REGISTRY_PW: ${{ secrets.DOCKERHUB_TOKEN }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      COSIGN_KEY_OR_KMS: ${{ secrets.COSIGN_KEY_STORE }}
